name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        python-version: ["2.7", 3.7, 3.8, 3.9, "3.10", 3.11]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pytest pytest-cov
      - name: Test with pytest
        run: |
          pytest --cov --cov-fail-under=100 -o log_cli=true -o log_cli_level=DEBUG
          python ./tests/test_examples.py
